# Dockerfile para backend (Node.js)
FROM node:16

# Establece directorio de trabajo dentro del contenedor
WORKDIR /home/node/app

# Copia package.json y package-lock.json para instalar dependencias
COPY package*.json ./

# Instala las dependencias necesarias
RUN npm install express mysql2 uuid

# Copia el resto del código de la app
COPY . .

# Expone el puerto que usa la app Node (8001 según tu docker-compose)
EXPOSE 8001

# Comando para arrancar la app
CMD ["npm", "start"]
